// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickTypeRecipe;
//
//    var recipe = Recipe.FromJson(jsonString);

namespace Recipe
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Recipe
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("version")]
        public double Version { get; set; }

        [JsonProperty("href")]
        public Uri Href { get; set; }

        [JsonProperty("results")]
        public Result[] Results { get; set; }
    }

    public partial class Result
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("href")]
        public Uri Href { get; set; }

        [JsonProperty("ingredients")]
        public string Ingredients { get; set; }

        [JsonProperty("thumbnail")]
        public string Thumbnail { get; set; }
    }

    public partial class Recipe
    {
        public static Recipe FromJson(string json) => JsonConvert.DeserializeObject<Recipe>(json,Recipe.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Recipe self) => JsonConvert.SerializeObject(self, Recipe.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
